title: Ĝis la
description: A project for me (us)...
url: gxisla.github.io
baseurl: gxisla.github.io

theme: jekyll-theme-minimal

google_analytics: UA-140799004-1

author:
    name: Matías Grioni
    email: matgrioni@gmail.com
    location: Seattle
    github: matgrioni
